name: Create PullRequest extensions update

on:
  schedule:
  - cron: "0 15 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup a package
      run: |
          sudo apt -y update
          sudo apt -y install jq
    - name: Setup a pip package
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
      run: |
        pip install yq
    - name: Run a script
      run: script/auto_update.sh
      env:
        GIST_URL: ${{ secrets.GIST_URL }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # The message to use when committing changes.
        commit-message: Update extensions.yml
        # The email address of the commit author.
        author-email: ${{ secrets.EMAIL }}
        # The name of the commit author.
        author-name: ${{ secrets.NAME }}
        # The title of the pull request.
        title: Update extensions.yml
        # The body of the pull request.
        body: Update
        # The pull request branch name.
        branch: auto_update
        # The branch suffix type.
        branch-suffix: short-commit-hash
