name: Create PullRequest extensions update

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.0
      - name: Setup
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run
        run: make run
        env:
          GIST_URL: ${{ secrets.GIST_URL }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # The message to use when committing changes.
          commit-message: Update extensions.yml
          # The email address of the commit author.
          author-email: ${{ secrets.EMAIL }}
          # The name of the commit author.
          author-name: ${{ secrets.NAME }}
          # The title of the pull request.
          title: Update extensions.yml
          # The body of the pull request.
          body: Update
          # The pull request branch name.
          branch: auto_update
          # The branch suffix type.
          branch-suffix: short-commit-hash
